name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # 最新版に更新
      - name: Set up Python
        uses: actions/setup-python@v5 # 最新版に更新
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pynput pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name "KeyCounter" main.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4 # ここがエラーの原因でした。v4に更新！
        with:
          name: KeyCounter-EXE
          path: dist/KeyCounter.exe
